enum TaskMap {
    title = 'Task',
    date = 'Do Date',
    priority = 'Priority',
    size = 'Size',
    recurring = 'Recurring',
    autoGenerated = 'Auto-Generated',
    status = 'Status',
    pillars = 'Pillars',
    projects = 'Projects',
    practices = 'Practices',
    people = 'People',

    eventId = 'Event ID',
    calendar = 'Calendar',
    calendarId = 'Calendar ID',
    lastSyncTime = 'Last Sync',
}

export default TaskMap;
